/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import javaapplication2.Library;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javaapplication2.ListItems;
/**
 *
 * @author Moustafa
 */
public class SimpleGUI extends javax.swing.JFrame {
    Library lb;
    DefaultTableModel dtm;
    /**
     * Creates new form SimpleGUI
     */
    public SimpleGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        lb = new Library();
        dtm = new DefaultTableModel();
        dtm.addColumn("Title");
        dtm.addColumn("Author");
        dtm.addColumn("ISBN");
        dtm.addColumn("Available?");
        dtm.addColumn("borrowDate");   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReturnItem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edt_Title = new javax.swing.JTextField();
        edt_ISBN = new javax.swing.JTextField();
        edt_Author = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cntrl_Type = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Items = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_ItemsList = new javax.swing.JButton();
        btn_BorrowItem = new javax.swing.JButton();
        btn_ReturnItem = new javax.swing.JButton();

        ReturnItem.setText("ReturnItem");
        ReturnItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnItemActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Author :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Title : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Type :");

        edt_Title.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edt_Title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edt_Title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_TitleActionPerformed(evt);
            }
        });

        edt_ISBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edt_ISBN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edt_ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_ISBNActionPerformed(evt);
            }
        });

        edt_Author.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edt_Author.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edt_Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_AuthorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("ISBN : ");

        cntrl_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physical Book", "EBook", "Reference Book", "CD", "DVD", "Journal" }));
        cntrl_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cntrl_TypeActionPerformed(evt);
            }
        });

        tbl_Items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Items);

        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_ItemsList.setText("Item list");
        btn_ItemsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ItemsListActionPerformed(evt);
            }
        });

        btn_BorrowItem.setText("Borrow Item");
        btn_BorrowItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrowItemActionPerformed(evt);
            }
        });

        btn_ReturnItem.setText("Return Item");
        btn_ReturnItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReturnItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edt_Title)
                            .addComponent(edt_ISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(edt_Author, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(cntrl_Type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_ItemsList, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_BorrowItem, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ReturnItem, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edt_Author, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cntrl_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ItemsList, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BorrowItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ReturnItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnItemActionPerformed

    private void edt_TitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_TitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_TitleActionPerformed

    private void edt_ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_ISBNActionPerformed

    private void edt_AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_AuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_AuthorActionPerformed

    private void cntrl_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cntrl_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cntrl_TypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!edt_Title.getText().isEmpty() && !edt_Author.getText().isEmpty() && !edt_ISBN.getText().isEmpty()){
            if(cntrl_Type.getSelectedItem().toString().equals("Physical Book")){
                PhysicalBook pb = new PhysicalBook(edt_Title.getText(), edt_Author.getText(),edt_ISBN.getText());
                lb.addItem(pb);
                JOptionPane.showMessageDialog(this,pb.toString()+" \nItem has been added");
                dtm.addRow(new Object[]{pb.getTitle(),pb.getAuthor(),pb.getISBN(),pb.getisAvailable(),pb.getBorrowDateTime()});
            }
            else if(cntrl_Type.getSelectedItem().toString().equals("EBook")){
                EBook eb = new EBook(edt_Title.getText(), edt_Author.getText(),edt_ISBN.getText());
                lb.addItem(eb);
                JOptionPane.showMessageDialog(this,eb.toString()+" \nItem has been added");
                dtm.addRow(new Object[]{eb.getTitle(),eb.getAuthor(),eb.getISBN(),eb.getisAvailable(),eb.getBorrowDateTime()});
            }
            else if(cntrl_Type.getSelectedItem().toString().equals("Reference Book")){
                ReferenceBook Rb = new ReferenceBook(edt_Title.getText(), edt_Author.getText(),edt_ISBN.getText());
                lb.addItem(Rb);
                JOptionPane.showMessageDialog(this,Rb.toString()+" \nItem has been added");
                dtm.addRow(new Object[]{Rb.getTitle(),Rb.getAuthor(),Rb.getISBN(),Rb.getisAvailable(),Rb.getBorrowDateTime()});
            }
            else if(cntrl_Type.getSelectedItem().toString().equals("CD")){
                CD cd = new CD(edt_Title.getText(), edt_Author.getText(),edt_ISBN.getText());
                lb.addItem(cd);
                JOptionPane.showMessageDialog(this,cd.toString()+" \nItem has been added");
                dtm.addRow(new Object[]{cd.getTitle(),cd.getAuthor(),cd.getISBN(),cd.getisAvailable(),cd.getBorrowDateTime()});

            }
            else if(cntrl_Type.getSelectedItem().toString().equals("DVD")){
                DVD dvd = new DVD(edt_Title.getText(), edt_Author.getText(),edt_ISBN.getText());
                lb.addItem(dvd);
                JOptionPane.showMessageDialog(this,dvd.toString()+" \nItem has been added");
                dtm.addRow(new Object[]{dvd.getTitle(),dvd.getAuthor(),dvd.getISBN(),dvd.getisAvailable(),dvd.getBorrowDateTime()});
            }
            else if(cntrl_Type.getSelectedItem().toString().equals("Journal")){
                Journal j = new Journal(edt_Title.getText(), edt_Author.getText(),edt_ISBN.getText());
                lb.addItem(j);
                JOptionPane.showMessageDialog(this,j.toString()+" \nItem has been added");
                dtm.addRow(new Object[]{j.getTitle(),j.getAuthor(),j.getISBN(),j.getisAvailable(),j.getBorrowDateTime()});
            }
            tbl_Items.setModel(dtm);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_ItemsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ItemsListActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ListItems(lb,this).setVisible(true);
    }//GEN-LAST:event_btn_ItemsListActionPerformed

    private void btn_BorrowItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrowItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Borrow(lb,this).setVisible(true);
    }//GEN-LAST:event_btn_BorrowItemActionPerformed

    private void tbl_ItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ItemsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbl_ItemsMouseClicked

    private void btn_ReturnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReturnItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Return(lb, this).setVisible(true);     
    }//GEN-LAST:event_btn_ReturnItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleGUI().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnItem;
    private javax.swing.JButton btn_BorrowItem;
    private javax.swing.JButton btn_ItemsList;
    private javax.swing.JButton btn_ReturnItem;
    private javax.swing.JComboBox<String> cntrl_Type;
    private javax.swing.JTextField edt_Author;
    private javax.swing.JTextField edt_ISBN;
    private javax.swing.JTextField edt_Title;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Items;
    // End of variables declaration//GEN-END:variables
}
